import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
  CreateDateColumn,
  Unique,
} from 'typeorm';
import { Client } from './client.entity';
import { JobOffer } from './job-offer.entity';
import { SendJob } from './send-job.entity';
import type { EmailResponse } from './email-response.entity';

export enum EmailSendStatus {
  RESERVED = 'reserved', // Picked by a worker but not sent yet
  PENDING_REVIEW = 'pending_review', // Generated by AI, awaiting manual approval
  APPROVED = 'approved', // Approved by user, ready to send
  SENT = 'sent',
  FAILED = 'failed',
  BOUNCED = 'bounced',
  REJECTED = 'rejected', // User rejected this email
}

@Entity('email_sends')
@Unique(['clientId', 'jobOfferId']) // Prevent sending same offer twice for same client
@Unique(['clientId', 'recipientEmail']) // Prevent sending to same email twice for same client (if business rule implies)
export class EmailSend {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Client)
  @JoinColumn({ name: 'client_id' })
  client: Client;

  @Column({ name: 'client_id' })
  clientId: number;

  @ManyToOne(() => JobOffer)
  @JoinColumn({ name: 'job_offer_id' })
  jobOffer: JobOffer;

  @Column({ name: 'job_offer_id' })
  jobOfferId: number;

  @ManyToOne(() => SendJob)
  @JoinColumn({ name: 'send_job_id' })
  sendJob: SendJob;

  @Column({ name: 'send_job_id', nullable: true })
  sendJobId: number;

  @Column({ name: 'recipient_email' })
  recipientEmail: string;

  @Column({
    type: 'enum',
    enum: EmailSendStatus,
    default: EmailSendStatus.RESERVED,
  })
  status: EmailSendStatus;

  @CreateDateColumn({ name: 'sent_at' })
  sentAt: Date;

  @Column({ name: 'message_id', nullable: true })
  messageId: string; // From Gmail API

  @Column({ type: 'text', nullable: true })
  content_snapshot: string; // optional: save generated email body

  @Column({ name: 'subject_snapshot', type: 'text', nullable: true })
  subjectSnapshot: string; // Save generated email subject

  @Column({ name: 'ai_generated', default: false })
  aiGenerated: boolean; // Whether email was generated by AI

  @Column({ name: 'ai_model', type: 'varchar', length: 50, nullable: true })
  aiModel: string | null; // The AI model used (e.g., 'gpt-4o-mini')

  @Column({ name: 'attachments_count', default: 0 })
  attachmentsCount: number; // Number of attachments included

  @Column({ name: 'reviewed_at', type: 'timestamp', nullable: true })
  reviewedAt: Date; // When the email was approved/rejected

  // Response tracking fields
  @Column({ name: 'gmail_thread_id', nullable: true })
  gmailThreadId: string; // Thread ID from Gmail API for tracking responses

  @Column({ name: 'has_responses', default: false })
  hasResponses: boolean; // Quick flag to indicate if there are responses

  @Column({ name: 'last_response_at', type: 'timestamp', nullable: true })
  lastResponseAt: Date | null; // When the last response was received

  @Column({ name: 'response_count', default: 0 })
  responseCount: number; // Number of responses received

  @OneToMany('EmailResponse', 'emailSend')
  responses: EmailResponse[];
}
